### ISSUE TITLE
keys and values are still in specs 

### ISSUE THREAD

**Issue by danielkcz** [WebReflection/es6-collections#5]
I have just checked draft from 18th of July and these two are still in there, so why you have removed them ?

```
23.1.3.8 Map.prototype.keys ( )
The following steps are taken:
1.  Let M  be the  this  value.
2.  Return the result of calling the CreateMapIterator abstract operation with arguments  M  and "key".

23.1.3.11 Map.prototype.values ( ) 
The following steps are taken:
1.  Let M  be the  this  value.
2.  Return the result of calling the CreateMapIterator abstract operation with arguments  M  and "value".
```

**Comment by englercj** [comment]
Ping! Any chance of getting iterators? I literally can't use this lib because I want to use the built-in `Set` and fallback to a polyfill but this lib acts differently than the spec. Set iteration via an iterator is extremely fast:

http://jsperf.com/es6-collection-iteration/7

So that is what I will be doing, but unfortunately not with this lib as the fallback due to lack of iterator support :(

**Comment by WebReflection** [comment]
I am pretty sure if the engine supports for/of you have native Set in there too, right ?
I am not sure if es6-shim would be a better, more obtrusive, polyfill for iterators too.

HHave a look: https://github.com/paulmillr/es6-shim/#safe-shims

**Comment by englercj** [comment]
So I'm actually using `es6-set` right now, but you don't need for/of to iterate a Set:

```js
var iterator = mySet.values();
var itVal;

while(!(itVal = iterator.next()).done) {
    itVal.value;
}
```

Which is basically how you *have* to do it if you want to use `Set` in browsers that implement it, and have code run with a polyfill (not talking about transpiling).

**Comment by WebReflection** [comment]
if that's how you have to do it anyway, what are you gaining in terms of performance? why not just the following?

```js
mySet.forEach(function (value) {
  // do what you have to do
});
```

I think es6-shim is the right way to go for a better compatibility. Transpilers might even support es6-shim fix/implementation in order to work properly, this old module was meant to introduce basic collections, not the whole new Iterator logic.

Not sure I should fix it, it seems right now overlapping or duplicated with what es6-shi fixed already.

What do you think? Why you need this module to be fixed?

**Comment by englercj** [comment]
Actually, just ran a jsperf and it looks like using `.forEach` and the while loop are both faster than using for/of, with the `.forEach` method being the fastest:

http://jsperf.com/es6-collection-iteration/8

I wasn't aware that you were deprecating this module in favor of es6-shim, the reason I don't use es6-shim is because I can't include *only* the set polyfill or *only* the map polyfill. I basically have to include everything or nothing, which is lame (why I am using `es6-set` right now). Note that I use CJS to organize my code and since all the polyfill are in a single file I can't include only a subset of it.

**Comment by WebReflection** [comment]
I am not necessarily deprecating this but I am not sure I want to fix the Iterator part. Iterator is a whole "thing" that if partially implemented coild break other code around. I rather stick with faster `forEach` also because Iterator is meant to be used with generators. I don't see any advantage in terms of performance, readability, or amount of RAM and GC operations, that would make me use a `for/of` instead of a `forEach` ... I don't see it practical, specially with Array-like structures.

Iterator is good, but not so useful with Sets or Maps, IMHO + I really don't have time to brng in a full Iterator logic that won't mess up with other possible polyfills that somehow fix Iterators in the whole env.

Hope this makes sense to you

**Comment by englercj** [comment]
@WebReflection Makes perfect sense, thanks for taking the time to explain it out. I still won't be using es6-shim for the foreseeable future, and I can't use for/of because I don't want to use a transpiler.

I want to use a set because the insert/unique check is much faster than an array, but the iteration is just so much slower (and that happens much more often in my case) so I may just switch to a pure array implementation.

**Comment by WebReflection** [comment]
if iteration is more frequent than inserting, how about this:

```js
Array.prototype.pushUnique = function () {
  for (var tmp, i = 0; i < arguments.length; i++) {
    tmp = arguments[i];
    if (this.indexOf(tmp) < 0) this.push(tmp);
  }
  return this.length;
};
```

you are penalized in insertion, but you won't compromise looping, which is the fewquent operation.

**Comment by englercj** [comment]
@WebReflection Which is exactly what I am going to do, I was using a set because the insertion would be more performant but I didn't realize until now just how slow the iteration was :(
